/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atmproject;

import java.awt.Image;
import java.awt.Toolkit;
import java.lang.String;

/**
 *
 * @author USER
 */
public class choose extends javax.swing.JFrame {

    /**
     * Creates new form choose
     */
    public choose() {
        initComponents();
    }
    int MyAccount;
    public choose(int AccountNum) {
        initComponents();
        MyAccount=AccountNum;
        AccNumib.setText(""+MyAccount);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imja = new javax.swing.JPanel();
        deposite = new javax.swing.JButton();
        withdraw = new javax.swing.JButton();
        Balance = new javax.swing.JButton();
        changepintb = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fastcash = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        AccNumib = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imja.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deposite.setText("DEPOSIT");
        deposite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depositeMouseClicked(evt);
            }
        });
        deposite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositeActionPerformed(evt);
            }
        });
        imja.add(deposite, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 195, -1));

        withdraw.setText("WITHDRAW");
        withdraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                withdrawMouseClicked(evt);
            }
        });
        withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawActionPerformed(evt);
            }
        });
        imja.add(withdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 195, -1));

        Balance.setText("BALANCE");
        Balance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BalanceMouseClicked(evt);
            }
        });
        Balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalanceActionPerformed(evt);
            }
        });
        imja.add(Balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 195, -1));

        changepintb.setText("CHANGE PIN");
        changepintb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changepintbMouseClicked(evt);
            }
        });
        imja.add(changepintb, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 195, -1));

        jLabel1.setText("                               CHOOSE YOUR TRANSACTION PLEASE");
        imja.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 329, 35));

        jLabel2.setText("ACCOUNT NUMBER");
        imja.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 120, 20));

        fastcash.setText("FAST CASH");
        fastcash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fastcashMouseClicked(evt);
            }
        });
        imja.add(fastcash, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 190, -1));

        jButton6.setText("MINISTATEMENT");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        imja.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 190, -1));

        AccNumib.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        AccNumib.setForeground(new java.awt.Color(255, 0, 0));
        AccNumib.setText("jLabel3");
        imja.add(AccNumib, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 90, 20));

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        imja.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 510, -1));

        jLabel3.setText("=");
        imja.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Log Out");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        imja.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imja, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imja, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depositeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositeActionPerformed
 
       
// TODO add your handling code here:
    }//GEN-LAST:event_depositeActionPerformed

    private void BalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BalanceActionPerformed

    private void withdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_withdrawActionPerformed

    private void depositeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositeMouseClicked
        
        new deposit(MyAccount).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_depositeMouseClicked

    private void withdrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawMouseClicked
        new withdraw(MyAccount).setVisible(true);
        this.dispose();    
    }//GEN-LAST:event_withdrawMouseClicked

    private void BalanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BalanceMouseClicked
         new balance(MyAccount).setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_BalanceMouseClicked

    private void changepintbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changepintbMouseClicked
        new Changepin(MyAccount).setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_changepintbMouseClicked

    private void fastcashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fastcashMouseClicked
          new Fastcash(MyAccount).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_fastcashMouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        new Ministatement(MyAccount).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
         new PASS().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new choose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccNumib;
    private javax.swing.JButton Balance;
    private javax.swing.JButton changepintb;
    private javax.swing.JButton deposite;
    private javax.swing.JButton fastcash;
    private javax.swing.JPanel imja;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton withdraw;
    // End of variables declaration//GEN-END:variables
}
